<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>WarnoLiteModdingTool.App</RootNamespace>
    <AssemblyName>WarnoLiteModdingTool</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Version>1.9.15</Version>
    <FileVersion>1.9.15.0</FileVersion>
    <InformationalVersion>1.9.15</InformationalVersion>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <ApplicationIcon>Assets/App.ico</ApplicationIcon>
    <AssemblyTitle>WARNO Lite Modding Tool</AssemblyTitle>
    <Product>WARNO Lite Modding Tool</Product>
    <Description>面向 WARNO Mod 新手的轻量化中文图形化编辑器</Description>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Localisation/en.tsv" />
    <Resource Include="Assets/App.ico" />
    <Resource Include="Assets/Emblems/*.png" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\WarnoLiteModdingTool.Core\WarnoLiteModdingTool.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="..\..\licenses\ZstdSharp-MIT.txt" Link="licenses\ZstdSharp-MIT.txt" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\..\README.md" Link="README.md" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\..\使用教程.md" Link="使用教程.md" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\..\USER_GUIDE.md" Link="USER_GUIDE.md" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\..\DEVELOPMENT.md" Link="DEVELOPMENT.md" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\..\LICENSE" Link="LICENSE" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\..\RELEASE_NOTES.md" Link="RELEASE_NOTES.md" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\..\RELEASE_NOTES.md" Link="发布说明.md" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
